options:
  enable-cgroups:
    type: boolean
    default: false
    description: |
       Enable GRUB cgroup overrides cgroup_enable=memory swapaccount=1. WARNING
       changing this option will reboot the host - use with caution on production
       services
  install_from_upstream:
    type: boolean
    default: false
    description: |
      Toggle installation from ubuntu archive vs the docker PPA
  http_proxy:
     type: string
     default:
     description: |
        URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
        environments where a proxy is the only option for routing to the
        registry to pull images
  https_proxy:
    type: string
    default:
    description: |
        URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
        environments where a proxy is the only option for routing to the
        registry to pull images
